[project]
name = "s2r-cod"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "gdown>=6.1.0",
    "opencv-python>=5.0.0.93",
    "scipy>=1.18.0",
    "torch>=2.11.0",
    "torchvision>=0.26.0",
    "tqdm>=4.70.0",
]

[project.scripts]
s2r-cod = "s2r_cod:main"

[build-system]
requires = ["uv_build>=0.12.0,<0.13.0"]
build-backend = "uv_build"

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true

[tool.uv.sources]
torch = [{ index = "pytorch-cu128" }]
torchvision = [{ index = "pytorch-cu128" }]
torchaudio = [{ index = "pytorch-cu128" }]
